name: Continues Integration

on: [push]

jobs:
  buildAndLint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Use Node.js 16.10
          uses: actions/setup-node@v3
          with:
            node-version: '16.10'
        - name: Install
          run: yarn install --frozen-lockfile --ignore-optional
        - name: Verify that the plugin metadta is correct
          run: yarn verify-package-metadata
        - name: Prettier validate
          run: yarn prettier:check
        - name: Lint
          run: yarn lint
        - name: Build chat
          run: yarn chat:build
        - name: Package
          run: yarn vsce:package

  test:
    name: Test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Use Node.js 16.10
          uses: actions/setup-node@v3
          with:
            node-version: '16.10'
        - name: Install
          run: yarn install --frozen-lockfile --ignore-optional
        - run: xvfb-run -a yarn test
          if: runner.os == 'Linux'
        - run: yarn test
          if: runner.os != 'Linux'
      
