name: Package vsix

on:
  workflow_dispatch:
    inputs:
      binaryVersion:
        type: string
        description: the version of the tabnine binary which will be packaged into this vsix file. it assumes it has been built and available to download
        required: true
      vsixVersion:
        type: string
        description: the version to tag this vsix with. should be valid semver format x.y.z
        required: true

jobs:
  build:
    name: Make vsix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '16.19'

      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: ${{ secrets.GCS_RELEASE_KEY }}

      - name: Set up Cloud SDK for gsutil
        uses: 'google-github-actions/setup-gcloud@v1'

      #          runs the binaries downloader script which will be packaged into this plugin
      - name: pull binaries
        run: VERSION=${{ inputs.binaryVersion }} ./binaries/downloadBinaries.sh
      #      https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
      - name: modify readme
        run: |
          echo "" > ./README.md
          echo "buildId: ${{ github.sha }}" >> ./README.md
          echo "" >> ./README.md
          echo "binary version: ${{ inputs.binaryVersion }}" >> ./README.md
      #        tags the version using npm version and then installs all the dependencies and then builds the actual vsix package
      - name: packaging
        id: packaging
        run: |
          npm version --no-git-tag-version ${{ inputs.vsixVersion }} \
          && yarn install --frozen-lockfile --ignore-optional \
          && ./buildOnPrem.sh \
          && mv ./tabnine-vscode-${{ inputs.vsixVersion }}.vsix tabnine-vscode-enterprise-${{ inputs.vsixVersion }}-${{ inputs.binaryVersion }}.vsix
          echo "{VSIX_PATH}={tabnine-vscode-enterprise-${{ inputs.vsixVersion }}-${{ inputs.binaryVersion }}.vsix} >> $GITHUB_OUTPUT
      #        helps to visualize which files were created
      - name: debug
        run: echo pwd; ls -lah

      - name: ⬆️ Upload vsix to GS
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ${{ steps.packaging.outputs.VSIX_PATH }}
          destination: latest-onprem-binaries/${{ env.BUILD_VERSION }}
